# aliases
alias bc="brew cleanup"
alias bci="brew info --cask"
alias bcin="brew install --cask"
alias bcl="brew list --cask"
alias bco="brew outdated --cask"
alias bcr="brew reinstall --cask"
alias bcu="brew upgrade --cask"
alias bi="brew info"
alias bin="brew install"
alias bl="brew list"
alias bo="brew outdated"
alias bog="brea outdated --greedy"
alias bu="brew update"
alias bun="brew uninstall"
alias bunc="brew uninstall --cask"
alias buncz="brew uninstall --cask --zap"
alias bup="brew upgrade"
alias bupc="brew upgrade --cask"
alias bupcg="brew upgrade --cask --greedy"
alias bupg="brew upgrade --greedy"
alias bubco="brew update && brew outdated --cask"
alias bubobco="brew update && brew outdated && brew outdated --cask"
alias gfu="git fetch upstream"
alias glon="git log --oneline -n 5"
alias gpom="git push origin main"
alias gs="git status"
alias lst="ls -alht"
alias r="/usr/local/Caskroom/miniforge/base/envs/r-console/bin/radian"

# shortcuts
omz=~/.oh-my-zsh/custom/custom.zsh
