# aliases
alias bc="brew cleanup"
alias bi="brew info"
alias bic="brew info --cask"
alias bin="brew install"
alias binc="brew install --cask"
alias bl="brew list"
alias blc="brew list --cask"
alias bo="brew outdated"
alias boc="brew outdated --cask"
alias bog="brew outdated --greedy"
alias brc="brew reinstall --cask"
alias bu="brew update"
alias buboc="brew update && brew outdated --cask"
alias bubocg="brew update && brew outdated --cask --greedy"
alias buboboc="brew update && brew outdated && brew outdated --cask"
alias bun="brew uninstall"
alias bunc="brew uninstall --cask"
alias buncz="brew uninstall --cask --zap"
alias bup="brew upgrade"
alias bupc="brew upgrade --cask"
alias bupcg="brew upgrade --cask --greedy"
alias bupg="brew upgrade --greedy"
alias gfu="git fetch upstream"
alias glon="git log --oneline -n 5"
alias gpom="git push origin main"
alias gs="git status"
alias lst="ls -alht"
alias r="/usr/local/Caskroom/miniforge/base/envs/r-console/bin/radian"

# shortcuts
omz=~/.oh-my-zsh/custom/custom.zsh
